export const AppStrings = {
    punchline:'Know Your Numbers, Grow Your Business',
    stock: 'Stock',
    daraz: 'Daraz',
    cash: 'Cash',
    packaging: 'Packaging',
    neworders: 'New Orders',
    products: 'Products',
    allstores: 'All Stores',
    totalbusiness: 'Total Business Value',
    orders: 'Orders',
    income: 'Income',
    ads: 'Ads',
    all: 'All',
    failed: 'Failed',
    shipped: 'Shipped',
    return: 'Return',
    sku: 'SKU',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    amountsettled: 'Amount Settled',
    weekinprogress: 'Week in Progress',
    name: 'Name',
    up: 'Up',
    q: 'Q',
    updatestock: 'Update Stock',
    addnewproduct: 'Add New Product',
    addnewitem: 'Add New Item',
    productname: 'Product Name',
    description: 'Description',
    add: 'Add',
    update: 'Update',
    selectproduct: 'Select Product',
    category: 'Category',
    enterquantity: 'Enter Quantity',
    addstock: 'Add Stock',
    minusstock: 'Minus Stock',
    symbol:{
        rs:'Rs'
    },
    darazInfo:'This is the approximate amount and stock worth of this amount in hands of daraz. It counts for all the stock which is currently in hands of daraz, all the pending amounts from daraz and all the money in form of ads balance. It does not count for any pending claims and vouchers of marketing solutions',
    stockInfo: 'This is the estimated worth of all the physical inventory currently available in your warehouse. It includes all SKUs that are packed, ready to be shipped, or in reserve. It does not include any stock that is in transit or at Daraz warehouses.',
    cashInfo: 'This represents the total available cash in hand and in bank accounts associated with your business. It includes liquid funds only and excludes receivables, investments, or any credit-based amounts.',
    packagingInfo: 'This is the approximate value of all available packaging materials including boxes, flyers, bubble wrap, and other supplies used for order fulfillment. It helps in tracking logistics readiness and packaging costs.',
    cancel:'Cancel',
    info:'Information',
    productDescription:'Product Description'
};
